modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "command_wand"
version = "${version}"
displayName = "command wand"
authors = "pat600130"
description = '''
a simple server mod for admins to give players any item and when used it will run a command modded or vanilla
'''
#logoFile = ""

[[dependencies.command_wand]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.command_wand]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.command_wand]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "SERVER"
